name: 'Run code linter'
description: 'Automatically lints your code'
author: 'MarvinJWendt'
inputs:
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'node12'
  main: 'lib/main.js'
